version: '2'

services:
  traefik:
    image: traefik:v1.7.16
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: traefik
    # command: apt install coreutils && chmod 600 ./acme.json

networks:
  web:
    external: true