version: '2'

services:
#   traefik:
#     image: traefik:v1.7.16
#     restart: always
#     ports:
#       - 80:80
#       - 443:443
#     networks:
#       - web
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - ./traefik.toml:/traefik.toml
#       - ./acme.json:/acme.json
#     container_name: traefik
#     # command: apt install coreutils && chmod 600 ./acme.json




  traefik:
    image: traefik:v2.1
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.file.directory=/etc/traefik/dynamic_conf
      - --providers.file.watch=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs/:/certs/:ro
      - ./traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro

networks:
  web:
    external: true

 